name: Regular base image update check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install skopeo
        run: sudo apt-get install -y skopeo
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Check change
        run: |
        
          skopeo inspect "docker://registry.access.redhat.com/ubi8/ubi:8.6" | grep -Po '(?<="Digest": ")([^"]+)' > .baseimagedigest
          docker run --rm --entrypoint sh -u 0 quay.io/cloudservices/ubi-trino:latest -c \
            'yum upgrade -y --security > /dev/null; rpm -qa | sort | sha256sum' \
            >> .baseimagedigest
      - name: Do change if the digest changed
        run: |
          git config user.name 'Update-a-Bot'
          git config user.email 'insights@redhat.com'
          git add .baseimagedigest
          if [ $(git status --porcelain | wc -l) -eq "0" ]; then echo "No new changes"; else ./bump-image-tag.sh; fi
          git commit -m "chore(image): update and rebuild image" || echo "No new changes"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'chore(image): update base image'
